### ISSUE TITLE
Window size is not fitting

### ISSUE THREAD

**Issue by KevinW1998** [suicvne/smbx-epmanager-ver3#3]
Weeeeeeeeeeeeeell......

![sizenotfit](https://cloud.githubusercontent.com/assets/4018533/4999107/45a17ef2-69df-11e4-8176-8b75eb876474.PNG)
I just wanted to test in once and that's what I get. All the important buttons are cut out from the window because of the too small window size.

**Comment by suicvne** [comment]
Do you have a certain DPI setting? Or font settings changed?

**Comment by KevinW1998** [comment]
I have standard 1920x1080 and I didn't change anything about font settings.

**Comment by suicvne** [comment]
Hmm well as far as I'm aware, this is an issue to do with scaling. Can you check for me? I'm under Ubuntu but if I remember correctly, I accessed it by

Right click on desktop>Personalize>Display in the left column and from there there's DPI related settings.

I'll try and see if there's a way to disable DPI scaling for this application programmatically.

**Comment by suicvne** [comment]
Until I get around to doing this myself, I found a couple of temporary solutions. They both come from [Microsoft](http://support.microsoft.com/kb/2900023).
- Disable DPI virtualization for the application. To do this, right-click the application’s shortcut and then click Properties. On the Compatibility tab, select Disable Display Scaling On High DPI Settings, and then click OK. This causes the text in the application to appear clearer. However, if the application does not correctly handle high DPI settings, this procedure may have adverse side effects such as truncated text and incorrectly sized graphical elements.

This is the setting I recommend toggling before you mess with overall DPI settings
- Lower the overall Windows DPI setting. To do this, open the Display item in Control Panel (or search for "dpiscaling" from the Start screen), and then adjust the slider under Change the size of all items. You may have to click to select the check box for Let me choose one scaling level for all my displays and then change the scale to 100 percent.

This will change it for everything and you will probably notice much smaller text on your display.

Let me know how these work with the program as I do not have a high DPI monitor to test this with

Cheers,

Mike

**Comment by suicvne** [comment]
Number 3! I want you to try out this build, it's the EXE only so just put it in your installation directory. I disabled AutoScaleMode for all forms so let me know if this fixes the issues with high DPI (if you have already unset the high dpi settings, reset them and try it out). [Download Here](https://dl.dropboxusercontent.com/u/62304851/SMBXEpisodeManager_DEBUGBUILD.zip)

**Comment by suicvne** [comment]
Fixed in 638568d43e
