### ISSUE TITLE
Window size v2 fail

### ISSUE THREAD

**Issue by KevinW1998** [suicvne/smbx-epmanager-ver3#4]
It is better now than the issue #3 but it still failes in the content area.

The new version:
![sizenotfitv2](https://cloud.githubusercontent.com/assets/4018533/5015328/1b0d0e9a-6a9d-11e4-9633-ad4289a33b0b.PNG)

**Comment by suicvne** [comment]
is that using the one i linked to you or is it using the one obtained via the update?

seems as though you're running the linked one as it still shows "_DEBUGBUILD" next to the version number.

**Comment by KevinW1998** [comment]
That's the one I've downloaded you linked to.

**Comment by suicvne** [comment]
Did you backup your original EXE? If not just use [this](http://mrmiketheripper.x10.mx/epmanager3/SMBXEpisodeManager_Latest.exe) instead. It's the latest that would normally be obtained via the update.

**Comment by KevinW1998** [comment]
Okay this version works!
